/* =========================================================
   ROLES & AUTH SETUP
========================================================= */

-- =========================================================
-- 1. ROLE TYPE
-- =========================================================

CREATE TYPE public.app_role AS ENUM ('admin', 'user');


-- =========================================================
-- 2. USER ROLES TABLE
-- =========================================================

CREATE TABLE public.user_roles (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id   UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  role      public.app_role NOT NULL,
  UNIQUE (user_id, role)
);

COMMENT ON TABLE public.user_roles IS 'Application roles for each user.';

-- Index for performance
CREATE INDEX idx_user_roles_user_id ON public.user_roles(user_id);


-- =========================================================
-- 3. DEFAULT ROLE ASSIGNMENT
-- =========================================================

CREATE OR REPLACE FUNCTION public.assign_default_role()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.user_roles (user_id, role)
  VALUES (new.id, 'user');
  RETURN new;
END;
$$;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE PROCEDURE public.assign_default_role();


-- =========================================================
-- 4. CUSTOM ACCESS TOKEN HOOK
-- =========================================================

CREATE OR REPLACE FUNCTION public.custom_access_token_hook(event JSONB)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  claims JSONB;
  user_role public.app_role;
BEGIN
  -- Get ONE role (simple model)
  SELECT role
  INTO user_role
  FROM public.user_roles
  WHERE user_id = (event->>'user_id')::UUID
  LIMIT 1;

  claims := event->'claims';

  IF user_role IS NOT NULL THEN
    claims := JSONB_SET(claims, '{user_role}', TO_JSONB(user_role));
  ELSE
    claims := JSONB_SET(claims, '{user_role}', 'null');
  END IF;

  event := JSONB_SET(event, '{claims}', claims);

  RETURN event;
END;
$$;

-- Permissions for Supabase auth system
GRANT USAGE ON SCHEMA public TO supabase_auth_admin;

GRANT EXECUTE
  ON FUNCTION public.custom_access_token_hook
  TO supabase_auth_admin;

REVOKE EXECUTE
  ON FUNCTION public.custom_access_token_hook
  FROM AUTHENTICATED, ANON, PUBLIC;

GRANT ALL
  ON TABLE public.user_roles
  TO supabase_auth_admin;

REVOKE ALL
  ON TABLE public.user_roles
  FROM AUTHENTICATED, ANON, PUBLIC;

ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow auth admin to read user roles"
ON public.user_roles
AS PERMISSIVE
FOR SELECT
TO supabase_auth_admin
USING (TRUE);


-- =========================================================
-- 5. ROLE CHECK FUNCTION
-- =========================================================

CREATE OR REPLACE FUNCTION public.jwt_has_role(target_role public.app_role)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT (auth.jwt() ->> 'user_role') = target_role::text;
$$;

CREATE OR REPLACE FUNCTION public.db_has_role(target_role public.app_role)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles ur
    WHERE ur.user_id = auth.uid()
      AND ur.role = target_role
  );
$$;

CREATE OR REPLACE FUNCTION public.has_role(target_role public.app_role)
RETURNS boolean
LANGUAGE sql
STABLE
AS $$
  SELECT
    public.jwt_has_role(target_role)
    OR public.db_has_role(target_role);
$$;
