/* =========================================================
   ROLES & AUTH SETUP
========================================================= */

-- =========================================================
-- 1. ROLE TYPE
-- =========================================================

create type public.app_role as enum ('admin', 'user');


-- =========================================================
-- 2. USER ROLES TABLE
-- =========================================================

create table public.user_roles (
  id        bigint generated by default as identity primary key,
  user_id   uuid references auth.users on delete cascade not null,
  role      public.app_role not null,
  unique (user_id, role)
);

comment on table public.user_roles is 'Application roles for each user.';

-- Index for performance
create index idx_user_roles_user_id on public.user_roles(user_id);


-- =========================================================
-- 3. DEFAULT ROLE ASSIGNMENT
-- =========================================================

create or replace function public.assign_default_role()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_roles (user_id, role)
  values (new.id, 'user');
  return new;
end;
$$;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.assign_default_role();


-- =========================================================
-- 4. CUSTOM ACCESS TOKEN HOOK
-- =========================================================

create or replace function public.custom_access_token_hook(event jsonb)
returns jsonb
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  claims jsonb;
  user_role public.app_role;
begin
  -- Get ONE role (simple model)
  select role
  into user_role
  from public.user_roles
  where user_id = (event->>'user_id')::uuid
  limit 1;

  claims := event->'claims';

  if user_role is not null then
    claims := jsonb_set(claims, '{user_role}', to_jsonb(user_role));
  else
    claims := jsonb_set(claims, '{user_role}', 'null');
  end if;

  event := jsonb_set(event, '{claims}', claims);

  return event;
end;
$$;

-- Permissions for Supabase auth system
grant usage on schema public to supabase_auth_admin;

grant execute
  on function public.custom_access_token_hook
  to supabase_auth_admin;

revoke execute
  on function public.custom_access_token_hook
  from authenticated, anon, public;

grant all
  on table public.user_roles
  to supabase_auth_admin;

revoke all
  on table public.user_roles
  from authenticated, anon, public;

alter table public.user_roles enable row level security;

create policy "Allow auth admin to read user roles"
on public.user_roles
as permissive
for select
to supabase_auth_admin
using (true);


-- =========================================================
-- 5. ROLE CHECK FUNCTION
-- =========================================================

create or replace function public.check_role(target_role public.app_role)
returns boolean
language sql
stable
as $$
  select coalesce(
    (auth.jwt() ->> 'user_role')::public.app_role = target_role,
    false
  );
$$;